### ISSUE TITLE
☂️ Umbrella: List of potential features / changes for a major version

### ISSUE THREAD

**Issue by amannn** [amannn/next-intl#779]
The big goal for the next major release is to get everything out of the way that a) makes the setup harder than necessary and b) could slow down feature development for the foreseeable future.

This is a list of ideas for API changes that we could potentially introduce in a major version:
- [x] Maybe we could automatically forward `formats` to Client Components with an option to opt-out (`formats={null}`). Keep in mind: https://github.com/amannn/next-intl/pull/633. See previously proposed docs changes in https://github.com/amannn/next-intl/pull/1046/commits/80332fc2a2daf66ea271617deb5abd2b3b10e46e.
- [x] Should nested `NextIntlClientProvider` inherit from each other? That would be very helpful to configure error handling as long as there's no better alternative (see https://github.com/amannn/next-intl/issues/611)
- [x] Go ESM-only? This has been supported [since Next.js 12](https://nextjs.org/blog/next-12#es-modules-support-and-url-imports). See also [Pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c?permalink_comment_id=3850849). `next.config.js` might be the trickiest one, but Node.js 22 (scheduled to be recommended by Autumn '24) supports `require`ing ESM from CJS too. Alternatively we could consider making an exception for `next-intl/plugin` ([ref](https://github.com/vercel/next.js/pull/71162)). If we do this, we can likely also go far a faster size limit preset.
- [x] Target more modern browsers. Currently we compile e.g. rest parameters, which have been supported by browsers since [a long time](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters#browser_compatibility). Not sure if this is a bug in `@babel/preset-env`, as "safari 12" results in rest params being compiled. In exchange, we can reduce bundle size. Does Next.js apply code transforms for backwards compat anyway to `node_modules`? See also various options in next.config.js like [bundlePagesRouterDependencies](https://nextjs.org/docs/app/building-your-application/upgrading/version-15#bundlepagesrouterdependencies).
- [x] Use modern JSX runtime consistently
  - [x] Babel: `['@babel/preset-react', {runtime: 'automatic'}]`
  - [x] TypeScript: `"jsx": "react-jsx"`
- [x] Remove deprecated [`defaultTranslationValues`](https://github.com/amannn/next-intl/pull/1411)
- [x] Remove support for detecting `src/i18n.ts`
- [x] Remove legacy navigation APIs (see https://github.com/amannn/next-intl/pull/1316)
- [x] Use `const` type params in `createMiddleware`, require TS >=5
- [x] Mandatory `locale` return value in `getRequestConfig`
- [x] Cookie changes: Decrease default cookie expiration to [a few hours](https://github.com/amannn/next-intl/issues/454#issuecomment-2238885859), remove `resolvedOptions.localeDetection` from condition in middleware (mention in changelog), add section to docs about possibility of using a longer max-age value (but you need to tell users next to your language picker)
- [x] https://github.com/amannn/next-intl/issues/1452
- [x] Maybe https://github.com/amannn/next-intl/issues/1377? (in case we overhaul the type registration API) Check this in combination with other types that receive a `locale` (e.g. routing APIs).
- [x] Remove `RequestLocaleLegacy` (only an internal change)
- [x] Maybe https://github.com/amannn/next-intl/issues/410?

(remaining tasks have been moved to https://github.com/amannn/next-intl/pull/1412)

No decision has been made on these so far, but if you have feedback about these points, please leave it here!

**Comment by amannn** [comment]
Adding the prefix for `getPathname` was also discussed in https://github.com/amannn/next-intl/discussions/785#discussioncomment-8159571.

**Comment by vricop** [comment]
Return typed messages from useMessages would be really nice.

Does anyone a workaround for this?

**Comment by vricop** [comment]
> Return typed messages from `useMessages` would be really nice.
> 
> Does anyone know a workaround for this?

I find out how to properly type safe the `useMessages` hook temporarily.

We can overload the function in our `./global.d.ts` types like this:

```ts
import en from 'messages/en.json'

export type Messages = typeof en

declare module 'next-intl' {
  interface IntlMessages extends Messages {}
  
  function useMessages(): IntlMessages;
}
```

![image](https://github.com/amannn/next-intl/assets/3494708/f630776e-5e93-4416-8bda-76671c2143cc)

**Comment by amannn** [comment]
All items mentioned above have been resolved in the [next-intl 4.0 beta](https://next-intl.dev/blog/next-intl-4-0)!
